server:
  port: 18080
  servlet:
    context-path: /wvp

spring:
  flyway:
    enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.176.169:3306/wvp?serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gengersoft.iot.vmp.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl